require 'open3'

WHITE_SPACES = " "
CONFIG_FOLDER = "/etc/sysconfig/network-scripts"

def bridges_to_persist()
    bridges = Hash.new

    stdin, stdout, stderr = Open3.popen3("brctl show")

    stdout.readlines.each do |line|
        fields = line.scan(/abiquo_\d/)

        unless fields.empty?
            bridge_name = fields[0]
            bridges[bridge_name] = {:bridge => bridge_name, :tag => bridge_name.scan(/\d/), :macs => []}
        end
    end

    bridges.each_pair do |bridge, atts|
        stdin, stdout, stderr = Open3.popen3("brctl showmacs #{bridge}")

        stdout.readlines.each do |line|
            atts[:macs].push line.split(WHITE_SPACES)[1].upcase if line.include? ":"
        end

        bridges.delete(bridge) if atts[:macs].empty?
    end

    bridges.each_pair do |bridge, atts|
        stdin, stdout, stderr = Open3.popen3("ifconfig")

        stdout.readlines.each do |line|
            atts[:macs].each do |mac|
                atts[:vlan] = line.split(WHITE_SPACES)[0] if line.include? ".#{atts[:tag]}" and line.include? mac
            end
        end

        bridges.delete(bridge) unless atts.has_key? :vlan
    end

    return bridges
end

def generate_bridge_file(bridge)
    open("#{CONFIG_FOLDER}/ifcfg-#{bridge}", "w") do |file|
        file.puts "# Autogenerated by Abiquo AIM"
        file.puts "DEVICE=#{bridge}"
        file.puts "TYPE=Bridge"
        file.puts "BOOTPROTO=none"
        file.puts "ONBOOT=yes"
    end
end

def generate_vlan_file(vlan, bridge)
    open("#{CONFIG_FOLDER}/ifcfg-abiquo_#{vlan}", "w") do |file|
        file.puts "# Autogenerated by Abiquo AIM"
        file.puts "VLAN=yes"
        file.puts "DEVICE=#{vlan}"
        file.puts "BOOTPROTO=none"
        file.puts "ONBOOT=yes"
        file.puts "BRIDGE=#{bridge}"
    end
end

bridges_to_persist.each_value do |config|
    generate_bridge_file config[:bridge]
    generate_vlan_file config[:vlan], config[:bridge]
end
